steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/another-doctor-471116/another-doctor-prod-repo/backend:latest', './apps/backend']
    id: 'build-backend'

images:
  - 'us-central1-docker.pkg.dev/another-doctor-471116/another-doctor-prod-repo/backend:latest'

options:
  substitution_option: 'ALLOW_LOOSE'