# Docker Compose override for development
# This file is automatically loaded by docker-compose
# It provides development-specific configurations

version: '3.8'

services:
  backend:
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      - ./apps/backend:/app/apps/backend:cached
      - ./packages:/app/packages:cached
    command: >
      sh -c "
        echo 'Starting development backend...';
        sleep 5;
        cd /app/apps/backend && alembic upgrade head;
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug;
      "

  frontend:
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./apps/frontend:/app:cached
      - ./packages/ts-utils:/packages/ts-utils:cached
      - /app/node_modules  # Prevent overwriting node_modules
      - /app/.next         # Prevent overwriting .next

  workers:
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./apps/backend:/app/apps/backend:cached
      - ./packages:/app/packages:cached
    command: >
      sh -c "
        echo 'Starting development workers...';
        sleep 10;
        cd /app/apps/backend;
        python -m rq worker --with-scheduler --url redis://redis:6379 --verbose;
      "

  # Only run essential services for development by default
  postgres:
    ports:
      - "5432:5432"
    
  redis:
    ports:
      - "6379:6379"
      
  qdrant:
    ports:
      - "6333:6333"
      - "6334:6334"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"