name = "another-doctor-workers"
compatibility_date = "2023-10-30"
main = "src/index.ts"

[env.production]
name = "another-doctor-workers"
route = "api.anotherdoctor.com/*"

[env.staging]
name = "another-doctor-workers-staging"
route = "api-staging.anotherdoctor.com/*"

[vars]
ENVIRONMENT = "production"

# Secrets (set via wrangler secret put):
# - R2_ACCESS_KEY_ID
# - R2_SECRET_ACCESS_KEY
# - BACKEND_API_URL
# - STRIPE_WEBHOOK_SECRET

[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "another-doctor-uploads"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"